Homework 0 -Eclectical Eagle Scouts```{r}
FizzBuzz = function(n)
{
  out = seq(n)
  out[(seq(n) %% 3)==0] = 'Fizz'
  out[(seq(n) %% 5)==0] = 'Buzz'
  out[(seq(n) %% 15)==0] = 'FizzBuzz'
  return(out)
}
```
========================================================

### Implementation

<!--
Use this section to implement the fizzbuzz function.
```{r,echo=T}
FizzBuzz = function(n)
{
  out = seq(n)
  out[(seq(n) %% 3)==0] = 'Fizz'
  out[(seq(n) %% 5)==0] = 'Buzz'
  out[(seq(n) %% 15)==0] = 'FizzBuzz'
  return(out)
}
```
## Define a function called FizzBuzz 
##Set input n as a sequence using sequence()
##Using []to subset out using a logical statement


This should include a short write up describing your appraoch
to implementing the function. Not both code formating / style
and your writeup matter for your overall grade.
-->


### Output

<!--
Use this section to show the output of your 
fizzbuzz function for integer values from 1 to 100.

No writeup is necessary for this section.
-->

```{r}
FizzBuzz(100)
```
